/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "sbhlnarifpbhfjabjbmi"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiaGxuYXJpZnBiaGZqYWJqYm1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1ODc5NTIsImV4cCI6MjA4NzE2Mzk1Mn0.9rqhU-r5kGZAjBkyyX9eUeHTIasbQDS2ARpVL1Lnp90"
